### ISSUE TITLE
Update to eslint-config@v4.2.0

### ISSUE THREAD

**Issue by beckybell13** [TechChange/eslint-config#30]
**Front-Ends**

- [x] https://github.com/TechChange/course-builder/pull/832
- [x] https://github.com/TechChange/components/pull/282
- [x] https://github.com/TechChange/FoggyBot/pull/1241
- [x] https://github.com/TechChange/princege/pull/932

**Node Services**

- [x] https://github.com/TechChange/Anacosti/pull/236
- [x] https://github.com/TechChange/Archives/pull/271
- [x] https://github.com/TechChange/branchav/pull/37
- [x] https://github.com/TechChange/Columbia/pull/249
- [x] https://github.com/TechChange/GalleryP/pull/228
- [x] https://github.com/TechChange/georgiaa/pull/29
- [x] https://github.com/TechChange/graphql/pull/7
- [x] https://github.com/TechChange/library/pull/12
- [x] https://github.com/TechChange/lrs-koa/pull/144
- [x] https://github.com/TechChange/mountver/pull/406
- [x] https://github.com/TechChange/navyyard/pull/121
- [x] https://github.com/TechChange/u-street/pull/58
- [x] https://github.com/TechChange/Waterfro/pull/569

**Other**

- [x] https://github.com/TechChange/node-auth/pull/18
- [x] https://github.com/TechChange/node-eventsystem/pull/8
- [x] https://github.com/TechChange/node-querybuilder/pull/13
- [x] https://github.com/TechChange/node-queryparser/pull/9
- [x] https://github.com/TechChange/node-test/pull/16
- [x] https://github.com/TechChange/pm-specs/pull/27
- [x] ~~mailmason~~
- [x] ~~tc-theme~~

**Comment by apettenati** [comment]
@beckybell13 

I need access to these, can you please grant?
node-auth
node-eventsystem
node-querybuilder
node-queryparser
pm-specs

Also not sure if I need to update this repo and how, do you want to tackle this one?
wp-platform

FYI confirmed these don't have eslint installed:
mailmason
tc-theme

**Comment by beckybell13** [comment]
@apettenati  Done! Whole team should have write access now to those now

**Comment by beckybell13** [comment]
wp-platform can be left alone. It's not worth cleaning that up and it's mostly php
